<template>
  <a-layout class="default-layout">
    <a-layout-sider
      breakpoint="lg"
      collapsedWidth="0"
      :style="{ overflow: 'auto', height: '100vh', position: 'fixed', left: 0 }"
    >
      <a-menu
        mode="inline"
        :defaultSelectedKeys="['1']"
        :defaultOpenKeys="['sub1']"
        :style="{ height: '100%', borderRight: 0 }"
      >
        <a-sub-menu key="sub1">
          <span slot="title">
            <a-icon type="user" />subnav 1
          </span>
          <a-menu-item key="1">option1</a-menu-item>
          <a-menu-item key="2">option2</a-menu-item>
          <a-menu-item key="3">option3</a-menu-item>
          <a-menu-item key="4">option4</a-menu-item>
        </a-sub-menu>
        <a-sub-menu key="sub2">
          <span slot="title">
            <a-icon type="laptop" />subnav 2
          </span>
          <a-menu-item key="5">option5</a-menu-item>
          <a-menu-item key="6">option6</a-menu-item>
          <a-menu-item key="7">option7</a-menu-item>
          <a-menu-item key="8">option8</a-menu-item>
        </a-sub-menu>
        <a-sub-menu key="sub3">
          <span slot="title">
            <a-icon type="notification" />subnav 3
          </span>
          <a-menu-item key="9">option9</a-menu-item>
          <a-menu-item key="10">option10</a-menu-item>
          <a-menu-item key="11">option11</a-menu-item>
          <a-menu-item key="12">option12</a-menu-item>
        </a-sub-menu>
      </a-menu>
    </a-layout-sider>
    <a-layout :style="{ marginLeft: '220px' }">
      <a-breadcrumb style="margin: 16px 0">
        <a-breadcrumb-item>Home</a-breadcrumb-item>
        <a-breadcrumb-item>List</a-breadcrumb-item>
        <a-breadcrumb-item>App</a-breadcrumb-item>
      </a-breadcrumb>
      <a-layout-content
        :style="{ background: '#fff', padding: '24px', marginRight: '20px', minHeight: '280px' }"
      >
        ...
        <br />Really
        <br />...
        <br />...
        <br />...
        <br />long
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />...
        <br />content
      </a-layout-content>
      <a-layout-footer
        :style="{ textAlign: 'center' }"
      >© 2019 Bali Decor Rental. All Rights Reserved.</a-layout-footer>
    </a-layout>
  </a-layout>
</template>

<style lang="scss" scoped>
.default-layout {
  margin-top: 40px;
}
</style>